config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#construction'
  get 'about', to: 'pages#about'
  get 'services', to: 'pages#services'
  get 'staff', to: 'pages#staff'
  get 'newsroom', to: 'pages#newsroom'
  get 'contact', to: 'pages#contact'
  get 'home', to: 'pages#home'
  resources :categories do
    resources :properties
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :properties, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :category
  validates :name, presence: true
  validates :value, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ControllerHelper
  before_action :require_admin
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_navbar_variables, only: [:index, :show, :new, :edit]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/concerns/controller_helper.rb
module ControllerHelper
  def require_admin
    current_user.nil? ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end

  def set_navbar_variables
    @navbar_category = Category.where(name: 'navbar').first
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include ControllerHelper
  before_action :require_admin, except: [:construction]
  before_action :set_navbar_variables

  def home; end

  def construction
    @disable_navbar = true
  end

  def about; end

  def services; end

  def staff; end

  def newsroom; end

  def contact; end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  include ControllerHelper
  before_action :require_admin
  before_action :set_property, only: [:edit, :update, :destroy]
  before_action :set_navbar_variables, only: [:new, :edit]

  def new
    @category = Category.find(params[:category_id])
    @property = @category.properties.build
  end

  def edit
    @category = @property.category
  end

  def update
    if @property.update(property_params)
      redirect_to category_path(@property.category)
    else
      render 'edit'
    end
  end

  def create
    @category = Category.find(params[:category_id])
    @property = @category.properties.create(property_params)
    if @property.save
      redirect_to category_path(@property.category)
    else
      render 'new'
    end
  end

  def destroy
    category = @property.category
    @property.destroy
    redirect_to category_path(category)
  end

  private

  def property_params
    params.require(:property).permit(:name, :value, :suffix)
  end

  def set_property
    @property = Property.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
  <%= form_with model: @category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, id: :category_name %>

    <%= f.submit %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <h2><%= link_to category.name, category_path(category) %></h2>
<% end %>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
  <table>
    <tr>
      <th>
        Name
      </th>
      <th>
        Value
      </th>
      <th>
        Suffix
      </th>
      <th>
        options
      </th>
    </tr>
    <% @category.properties.each do |property| %>
      <tr>
        <td>
          <%= property.name %>
        </td>
        <td>
          <%= property.value %>
        </td>
        <td>
          <%= property.suffix %>
        </td>
        <td>
          <%= link_to 'edit', edit_category_property_path(@category, property) %>
          <%= button_to 'delete', [@category, property], method: :delete,
                                data: { confirm: 'Are you sure you want to delete?' } %>
        </td>
      </tr>
    <% end %>
  </table>
<%= link_to 'New Property', new_category_property_path(@category) %>

app/views/layouts/_navbar.html.erb
<nav>
  <%= link_to image_tag('bifrost-logo.jpg'), '/home', class: 'brand' %>

  <input id='trigger' type='checkbox'>

  <label for='trigger' id='nav-toggle'>
    <span></span>
  </label>

  <div class='link-container'>
    <ul>
      <li>
        <a href='/about'>
          About Us
        </a>
      </li>
      <li>
        <a href='/services'>
          Services
        </a>
      </li>
      <li>
        <a href='/staff'>
          Staff
        </a>
      </li>
      <li>
        <a href='/newsroom'>
          Newsroom
        </a>
      </li>
      <li>
        <a href='/contact'>
          Contact Us
        </a>
      </li>
    </ul>
  </div>
</nav>

<% if @navbar_category %>
  <% @navbar_category.properties.each do |property| %>
    <%= content_tag 'div', id: 'navbar_category', data: { name: property.name,
                                                          value: property.value,
                                                          suffix: property.suffix } do %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <title>Bifrost</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% if @disable_navbar %>
      <%= yield %>
    <% else %>
      <%= render 'layouts/navbar' %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>

app/views/pages/construction.html.erb
<%= image_tag('northern-lights.jpg') %>

<div class='foreground-text'>
  <h1 align='center'>
    The Bifrost Environmental and Remediation Services Website is Currently Under Construction
  </h1>
</div>

app/views/pages/home.html.erb
hi Mark

app/views/pages/serives.html.erb
services page

app/views/properties/_form.html.erb
<%= render 'shared/errors', obj: @property %>
<%= form_with(model: [ @category, @property ]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, id: :property_name %>

  <%= f.label :value %>
  <%= f.text_field :value, id: :property_value %>

  <%= f.label :suffix %>
  <%= f.text_field :suffix, id: :property_suffix %>

  <%= f.submit %>
<% end %>

app/views/properties/edit.html.erb
<%= render 'form' %>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2>
    <%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:
  </h2>
  <u1>
    <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </u1>
<% end %>